config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(os.environ.get("DJANGO_ADMIN", "admin/"), admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("add/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFabsView.as_view(), name="see-favs"),
]

reservations/urls.py
from django.urls import path
from . import views


app_name = "Reervations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>",
        views.create,
        name="create",
    ),
    path("<int:pk>", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:user>/list/", views.ReservationListView.as_view(), name="list"),
    path("<int:pk>/<str:verb>/", views.edit_reservation, name="edit"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.DeleteRoomView.as_view(), name="delete"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoview.as_view(),
        name="edit-photo",
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("login/naver/", views.naver_login, name="naver-login"),
    path("login/naver/callback/", views.naver_callback, name="naver-callback"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>/", views.complate_verification, name="verify"),
    path("logout/", views.log_out, name="logout"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]

templates/partials/footer.html
{% load i18n %}
<footer class="mt-14 p-10 container mx-auto text-center border-t font-medium text-gray-500">
    <div class="flex flex-col">
        <div>{% trans "Welcome to the new world" %}.</div>
        <div class="mt-2">&copy; 2021 Maxbnb, Inc. {% trans "All rights reserved" %}.</div>
    </div>
    <div class="flex items-center justify-center mt-10">
        
        {% get_current_language as LANGUAGE_CODE %}
        <select name="" id="js-lang" class="w-max h-full">
            <option value="en" {% if LANGUAGE_CODE == 'en' %}selected{% endif %}>English</option>
            <option value="ko" {% if LANGUAGE_CODE == 'ko' %}selected{% endif %}>한국어</option>
        </select>
    </div>
</footer>

templates/partials/messages.html
{% if messages %}
    <ul class="absolute mx-auto top-0 left-0 right-0 flex justify-center">
        {% for message in messages %}
        <li class="message font-medium bg-gray-500 rounded-full z-10 text-white py-4 px-6 w-64 text-center {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/partials/nav.html
{% load i18n %}
<ul class="flex items-center justify-end text-sm font-medium w-full h-full">
     {% if user.is_authenticated %}
        <li class="nav_link">
            <a href="{% url 'users:switch-hosting' %}">
                {% if request.session.is_hosting %}
                    <div>{% trans "Stop Hosting" %}</div>
                {% else %}
                    <div>{% trans "Start Hosting" %}</div>
                {% endif %}
            </a>
        </li>
        {% if request.session.is_hosting %}
            <li class="nav_link">
                <a href="{% url 'rooms:create' %}">
                    <div>{% trans "Create Room" %}</div>
                </a>
            </li>
        {% endif %}
        <li class="nav_link">
            <a href="{% url 'reservations:list' user.pk %}">
                <div>{% trans "My Reservation" %}</div>
            </a>
        </li>
        <li class="nav_link">
            <a href="{% url 'lists:see-favs' %}">
                <div>
                    {% trans "Favs" %}{% if user.list.rooms.count > 0 %}({{user.list.rooms.count}}){% endif %}
                </div>
            </a>
        </li>
        <li class="nav_link">
            <a href="{{user.get_absolute_url}}">
                <div>{% trans "Profile" %}</div>
            </a>
        </li>
        <li class="nav_link">
            <a href="{% url 'users:logout' %}">
                <div>{% trans "Log out" %}</div>
            </a>
        </li>
    {% else %} 
        <li class="nav_link">
            <a href="{% url 'users:login' %}">
                <div>{% trans "Log in" %}</div>
            </a>
        </li>
        <li class="nav_link">
            <a href="{% url 'users:signup' %}">
            <div>{% trans "Sign Up" %}</div>
            </a>
        </li>
    {% endif %}
    
</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url 'users:github-login' %}" class="btn text-center border-gray-500 text-gray-700 mb-2 hover:bg-gray-700 hover:text-white">
        <i class="fab fa-github fa-lg mr-2"></i> Continue with Github
    </a>
    <a href="{% url 'users:kakao-login' %}" class="btn text-center border-yellow-400 hover:border-transparent text-yellow-400 mb-2 bg-white hover:bg-yellow-400 hover:text-white">
        <i class="fas fa-comment fa-lg mr-2"></i> Continue with Kakao
    </a>
    <a href="{% url 'users:naver-login' %}" class="btn text-center border-green-600 hover:border-transparent text-green-600 mb-2 bg-white hover:bg-green-600 hover:text-white">
        <div class="flex justify-center items-center">
            <div class="text-xl font-extrabold mr-3">N</div>
            <div>Continue with Naver</div>
        </div>
    </a>
</div>

<div class="flex items-center w-full my-12">
    <div class="h-px w-full bg-gray-400"></div>
    <div class=" text-gray-700 font-medium mx-4 text-sm">or</div>
    <div class="h-px w-full bg-gray-400"></div>
</div>