config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(os.environ.get("DJANGO_ADMIN", "admin/"), admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("add/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFabsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.DeleteRoomView.as_view(), name="delete"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoview.as_view(),
        name="edit-photo",
    ),
]

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    """Search Form Definition"""

    city = forms.CharField(initial="Anywhere", required=False)
    country = CountryField(blank=True, blank_label="Select Country").formfield()
    price = forms.IntegerField(required=False)
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any Kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False, min_value=5)
    guests = forms.IntegerField(required=False, min_value=1)
    bedrooms = forms.IntegerField(required=False, min_value=0)
    beds = forms.IntegerField(required=False, min_value=0)
    baths = forms.IntegerField(required=False, min_value=0)

    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)

    # amenities = forms.ModelMultipleChoiceField(
    #     queryset=models.Amenity.objects.all(),
    #     widget=forms.CheckboxSelectMultiple,
    #     required=False,
    # )
    # facilities = forms.ModelMultipleChoiceField(
    #     queryset=models.Facility.objects.all(),
    #     widget=forms.CheckboxSelectMultiple,
    #     required=False,
    # )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, *args, **kwargs):
        photo = super().save(commit=False)
        return photo


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "address",
            "price",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.http.response import Http404
from django.urls.base import reverse_lazy
from django.views.generic import ListView, DetailView, View, UpdateView
from django.shortcuts import redirect, render
from django.urls import reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import DeleteView, FormView
from users import mixins as user_mixins
from . import models, forms


class HomeView(ListView):

    """HomeView Definition"""

    model = models.Room
    paginate_by = 24
    paginate_orphans = 5
    ordering = "-created"
    page_kwarg = "page"
    context_object_name = "rooms"


class RoomDetail(DetailView):

    """Room Detail Definition"""

    model = models.Room


class SearchView(View):

    """Search View Definition"""

    def get(self, request):
        city = request.GET.get("city")
        if city:
            form = forms.SearchForm(request.GET)  # form 내용 받아옴
            if form.is_valid():
                # cleaned_data.get 으로 form 안의 data 를 바로 받을 수 있음
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                price = form.cleaned_data.get("price")
                room_type = form.cleaned_data.get("room_type")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                # amenities = form.cleaned_data.get("amenities")  # queryset 으로 받음
                # facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city
                if country != "":
                    filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                # for amenity in amenities:
                #     filter_args["amenities"] = amenity

                # for facility in facilities:
                #     filter_args["facilities"] = facility

                qs = models.Room.objects.filter(**filter_args).order_by("-created")
                # paginator 사용 시 queryset 의 order 기준이 필요함

                paginator = Paginator(qs, 12, orphans=6)

                page = request.GET.get("page", 1)

                rooms = paginator.get_page(page)

                return render(
                    request,
                    "rooms/search.html",
                    {
                        "form": form,
                        "rooms": rooms,
                    },
                )
        else:
            form = forms.SearchForm()

        return render(request, "rooms/search.html", {"form": form})


class EditRoomView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Room
    template_name = "rooms/room_edit.html"
    success_message = "Room Updated"

    fields = (
        "name",
        "description",
        "country",
        "city",
        "address",
        "price",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


class DeleteRoomView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, DeleteView):
    model = models.Room
    success_message = "Room Deleted"
    success_url = reverse_lazy("core:home")
    template_name = "rooms/room_delete.html"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(DeleteRoomView, self).delete(request, *args, **kwargs)


class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "Can't delete photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo Deleted")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoview(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    fields = ("caption",)
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotoView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreatePhotoForm
    template_name = "rooms/photo_create.html"

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        photo = form.save(pk)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        form.save_m2m()
        messages.success(self.request, "Room Created")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/main_picture.html
{% load i18n %}
{% load static %}
<div style="background-image: url('{% static "image/main_bg.webp" %}')"; class="hidden lg:block bg-cover lg:w-full bg-center lg:h-90vh lg:-mt-16">
    <div class="h-full flex items-center justify-center flex-col">
        <div class="text-xl font-medium mt-40">{% trans "Not sure any to go? Perfect" %}.</div>
        <a href="{% url 'rooms:search' %}?city=Anywhere">
            <div class="mt-5 px-14 py-5 bg-white rounded-full shadow-xl text-xl font-medium cursor-pointer hover:shadow-2xl transition-all">
                <div>{% trans "I'm flexible" %}</div>
            </div>    
        </a>
    </div>
</div>
<div style="background-image: url('{% static "image/md_main_bg.webp" %}')"; class="hidden md:block lg:hidden bg-cover bg-center md:w-full md:h-75vh">
    <div class="h-full flex items-center justify-center flex-col">
        <div class="text-xl font-medium mt-40">{% trans "Not sure any to go? Perfect" %}.</div>
        <a href="{% url 'rooms:search' %}?city=Anywhere">
            <div class="mt-5 px-14 py-5 bg-white rounded-full shadow-xl text-xl font-medium cursor-pointer hover:shadow-2xl transition-all">
                <div>{% trans "I'm flexible" %}</div>
            </div>    
        </a>
    </div>
</div>
<div style="background-image: url('{% static "image/sm_main_bg.webp" %}')"; class="block md:hidden bg-cover bg-center h-85vh w-full">
    <div class="h-full flex items-center justify-center flex-col">
        <div class="text-xl font-medium mt-40">{% trans "Not sure any to go? Perfect" %}.</div>
        <a href="{% url 'rooms:search' %}?city=Anywhere">
            <div class="mt-5 px-14 py-5 bg-white rounded-full shadow-xl text-xl font-medium cursor-pointer hover:shadow-2xl transition-all">
                <div>{% trans "I'm flexible" %}</div>
            </div>    
        </a>
    </div>
</div>

templates/rooms/photo_create.html
{% extends 'base.html' %}

{% block page_title %}Upload Photo{% endblock page_title %}

{% block search_bar %}{% endblock search_bar %}

{% block content %}
    <div class="container md:w-6/12 lg:w-5/12 xl:w-2/5 mx-auto mt-40 mb-24 flex flex-col items-center border p-6 border-gray-300">
        {% include 'mixins/room/room_form.html' with form=form cta="Upload Photo" %}
    </div>
{% endblock content %}

templates/rooms/photo_edit.html
{% extends 'base.html' %}

{% block page_title %}Update Photo{% endblock page_title %}

{% block search_bar %}{% endblock search_bar %}

{% block content %}
    <div class="container md:w-6/12 lg:w-5/12 xl:w-2/5 mx-auto mt-40 mb-24 flex flex-col items-center border p-6 border-gray-300">
        {% include 'mixins/room/room_form.html' with form=form cta="Update Photo" %}
    </div>
{% endblock content %}

templates/rooms/room_create.html
{% extends 'base.html' %}

{% block page_title %}Create Room{% endblock page_title %}

{% block search_bar %}{% endblock search_bar %}

{% block content %}
    <div class="container md:w-6/12 lg:w-5/12 xl:w-2/5 mx-auto mt-40 mb-24 flex flex-col items-center border p-6 border-gray-300">
        {% include 'mixins/room/room_form.html' with form=form cta="Create Room" %}
    </div>
{% endblock content %}

templates/rooms/room_delete.html
{% extends 'base.html' %}

{% block page_title %}Delete Room{% endblock page_title %}

{% block search_bar %}{% endblock search_bar %}

{% block content %}
    <div class="container md:w-6/12 lg:w-5/12 xl:w-2/5 mx-auto mt-40 mb-24 flex flex-col items-center border p-6 border-gray-300">
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ room.name }}"?</p>
            <button class="btn-link mt-5 text-center">Delete Room</button>
        </form>
    </div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends 'base.html' %} 
{% load is_booked i18n on_favs %}


{% block page_title %}
    {{room.name}} 
{% endblock page_title %} 

{% block content %} 
    <div class="container max-w-6xl h-full mx-auto mb-20 mt-28">
        <div class="flex items-center justify-between">
            <div class="text-2xl font-medium">{{room.name}}</div>
            <div class="w-12">
                {% if not user.is_anonymous %}
                    {% on_favs room as on_favs_boolean %}
                    {% if on_favs_boolean %}
                        <a href="{% url 'lists:toggle-room' room.pk %}?action=remove" class="text-2xl text-red-400"><i class="fas fa-heart"></i></a>    
                    {% else %}
                        <a href="{% url 'lists:toggle-room' room.pk %}?action=add" class="text-2xl text-red-400"><i class="far fa-heart"></i></a>    
                    {% endif %}
                {% endif %}
            </div>
        </div>
        <div class="flex items-center mt-2 text-sm text-gray-500">
            <div class="flex items-center mr-2">
                <i class="fas fa-star text-red-500 text-xs mr-1"></i> 
                <div class="font-medium text-black mr-1 ">{{room.total_rating}}</div>
                <div class="font-medium underline">({{room.reviews.count}} review{{room.reviews.count|pluralize}})</div>
            </div>
            {% if room.host.superhost %}
            <div class="flex items-center mr-2">
                <div class="mr-2">·</div>
                <i class="fas fa-medal text-red-500 mr-1"></i>
                <div>SuperHost</div>
            </div>
            {% endif %}
            <div class="flex items-center">
                <div class="mr-2">·</div>
                <div class="mr-1 underline font-medium">{{room.city}},</div>
                <div class="underline font-medium">{{room.country.name}}</div>
            </div>
        </div>
        <div class="flex mt-5 h-50vh">
            <div class="h-full w-1/2 bg-cover bg-center rounded-l-xl mr-2 cursor-pointer filter hover:brightness-90 transition-all duration-300" style="background-image :url({{room.first_photo}}) "></div>
            <div class="h-full w-1/2 grid grid-cols-2 gap-2">
                {% for photo in room.get_next_four_photos %}
                    <div style="background-image : url({{photo.file.url}})" class="w-full h-full bg-cover bg-center {% if forloop.counter == 2 %} rounded-tr-lg {% endif %} {% if forloop.counter == 4 %} rounded-br-lg {% endif %} filter hover:brightness-90 cursor-pointer transition-all duration-300"></div>
                {% endfor %}
            </div>
        </div>

        <div class="mt-10 flex">
            <div class="w-7/12">
                <div class="flex items-center justify-between">
                    <div class="">
                        <div class="text-2xl font-medium">{{room.room_type}} hosted by {{room.host.first_name}}</div>
                        <div class="flex items-center">
                            <div class="flex mr-1">
                                <div>{{room.guests}} guest{{room.guests|pluralize}}</div>
                            </div>
                            <div class="flex mr-1">
                                <div class="mr-1">·</div>
                                <div>{{room.bedrooms}} bedroom{{room.bedrooms|pluralize}}</div>
                            </div>
                            <div class="flex mr-1">
                                <div class="mr-1">·</div>
                                <div>{{room.beds}} bed{{room.beds|pluralize}}</div>
                            </div>
                            <div class="flex">
                                <div class="mr-1">·</div>
                                <div>{{room.baths}} bath{{room.baths|pluralize}}</div>
                            </div>
                        </div>
                    </div>
                    <div class="flex">
                        <a href="{{room.host.get_absolute_url}}">
                            <div>{% include 'mixins/user_avatar.html' with user=room.host amount=14 %}</div>
                        </a>
                        <div class="-ml-5 mt-8">
                            {% if room.host.superhost %}
                            <i class="fas fa-crown fa-lg text-yellow-500"></i>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="border-section"></div>
                <p class="mt-5">
                    {{room.description}}
                </p>
                <div class="border-section"></div>
                <div>
                    <div class="text-2xl font-medium mt-5">What this place offers </div>
                    <div class="text-xl font-medium mt-5">Amenities</div>
                    <div class="grid grid-cols-2 mt-2">
                        {% for amenity in room.amenities.all %}
                        <div class="mb-1">{{amenity.name}}</div class="mb-10">
                        {% endfor %}
                    </div>
                    <div class="text-xl font-medium mt-5">Facilities</div>
                    <div class="grid grid-cols-2 mt-2">
                        {% for facility in room.facilities.all %}
                        <div class="mb-1">{{facility.name}}</div class="mb-10">
                        {% endfor %}
                    </div>
                    <div class="text-xl font-medium mt-5">House Rule</div>
                    <div class="grid grid-cols-2 mt-2">
                        {% for house_rule in room.house_rules.all %}
                        <div class="mb-1">{{house_rule.name}}</div class="mb-10">
                        {% endfor %}
                    </div>
                </div>
                
                
            </div>
            <div class="w-5/12 px-8">
            {% if room.host == user %}
                <a href="{% url 'rooms:edit' room.pk %}" class="py-3 rounded-lg text-white bg-green-500 block text-center">Edit room</a>
                <a href="{% url 'rooms:delete' room.pk %}" class="btn-link block text-center mt-5">Delete room</a>
            {% else %}
                {% if not request.session.is_hosting %}
                    {% for calender in room.get_calenders %}
                        <div class="mb-20 px-20">
                            <div class="text-center mb-5 font-medium">
                                {{calender.get_month}} / {{calender.year}}
                            </div>
                            <div class="grid grid-cols-7 gap-2 text-center">
                            {% for day in calender.day_names %}
                                <div class="font-medium">{{day}}</div>
                            {% endfor %}
                            {% for day in calender.get_days %}
                                {% is_booked room day as is_booked_bool %}
                                {% if day.number != 0 %}
                                    {% if day.past %}
                                        <div class="bg-gray-200 rounded text-gray-300 p-1 w-full cursor-not-allowed">{{day}}</div>
                                    {% elif is_booked_bool %}
                                        <div class="bg-gray-200 rounded text-gray-400 p-1 w-full cursor-not-allowed line-through">{{day}}</div>
                                    {% else %}
                                        <a href="{% url 'reservations:create' room.pk day.year day.month day.number %}" class="bg-gray-200 rounded text-gray-600 p-1 w-full hover:bg-red-400 hover:text-white hover:font-medium cursor-pointer">
                                            {{day}}
                                        </a>
                                    {% endif %}
                                {% else %}
                                    <div></div>
                                {% endif %}
                            {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                <div>Sorry, You can't make a reservation during hosing mode.</div>
                <div>Please click 'Stop Hosting' on the navigation.</div>
                {% endif %}
            {% endif %} 
            
                
            </div>
        </div>
        <div class="border-section"></div>
        <div class="text-xl font-medium mt-5">Reviews</div>
        {% if room.reviews.count > 0 %}
        <div class="flex items-center text-xl mt-3">
            <i class="fas fa-star text-red-500 text-base mr-2"></i> 
            <div class="font-medium text-black mr-1 ">{{room.total_rating}}</div>
            <div class="mx-2">·</div>
            <div class="font-medium">{{room.reviews.count}} review{{room.reviews.count|pluralize}}</div>
        </div>
        <div class="grid grid-cols-2 mt-2">
            <div class="grid grid-cols-2 pr-24 mt-2"> 
                <div>Acurrancy </div>
                <div class="flex w-full items-center justify-end">
                    <div class=" md:w-24 lg:w-48 h-1 bg-gray-300 rounded-full mr-5 relative">
                        <div class="h-1 bg-red-400 rounded-full" style="width:{{room.acurrancy_percent}}%"></div>
                    </div>
                    <div>{{room.total_acurrancy}}</div>
                </div>
            </div>
            <div class="grid grid-cols-2 pr-24 mt-2"> 
                <div>Communication </div> 
                <div class="flex w-full items-center justify-end">
                    <div class=" md:w-24 lg:w-48 h-1 bg-gray-300 rounded-full mr-5 relative">
                        <div class="h-1 bg-red-400 rounded-full" style="width:{{room.communication_percent}}%"></div>
                    </div>
                    <div>{{room.total_communication}}</div>
                </div>
            </div>
            <div class="grid grid-cols-2 pr-24 mt-2"> 
                <div>Cleanliness </div> 
                <div class="flex w-full items-center justify-end">
                    <div class=" md:w-24 lg:w-48 h-1 bg-gray-300 rounded-full mr-5 relative">
                        <div class="h-1 bg-red-400 rounded-full" style="width:{{room.cleanliness_percent}}%"></div>
                    </div>
                    <div>{{room.total_cleanliness}}</div>
                </div>
            </div>
            <div class="grid grid-cols-2 pr-24 mt-2"> 
                <div>Location </div> 
                <div class="flex w-full items-center justify-end">
                    <div class=" md:w-24 lg:w-48 h-1 bg-gray-300 rounded-full mr-5 relative">
                        <div class="h-1 bg-red-400 rounded-full" style="width:{{room.location_percent}}%"></div>
                    </div>
                    <div>{{room.total_location}}</div>
                </div>
            </div>
            <div class="grid grid-cols-2 pr-24 mt-2"> 
                <div>Check In </div> 
                <div class="flex w-full items-center justify-end">
                    <div class=" md:w-24 lg:w-48 h-1 bg-gray-300 rounded-full mr-5 relative">
                        <div class="h-1 bg-red-400 rounded-full" style="width:{{room.check_in_percent}}%"></div>
                    </div>
                    <div>{{room.total_check_in}}</div>
                </div>
            </div>
            <div class="grid grid-cols-2 pr-24 mt-2"> 
                <div>Value </div> 
                <div class="flex w-full items-center justify-end">
                    <div class=" md:w-24 lg:w-48 h-1 bg-gray-300 rounded-full mr-5 relative">
                        <div class="h-1 bg-red-400 rounded-full" style="width:{{room.value_percent}}%"></div>
                    </div>
                    <div>{{room.total_value}}</div>
                </div>
            </div>
        </div>
        <div class="grid grid-cols-2 gap-5 mt-10">
            {% for review in room.reviews.all %}
                <div class="">
                    <div class="flex items-center justify-between">
                        <div class="flex items-center">
                            <div class="mr-5">{% include 'mixins/user_avatar.html' with user=review.user amount=14 %}</div>
                            <div>
                                <div class="font-medium">{{review.user.first_name}}</div>
                                <div>{{review.created|date:"F Y"}}</div>
                            </div>
                        </div>
                        {% if review.user == user %}
                        <a href="{% url 'reviews:delete' room.pk review.pk %}" class="text-gray-400 hover:text-gray-700 mr-20">
                            <i class="far fa-trash-alt"></i>
                        </a>
                        {% endif %}
                    </div>
                    <div class="mt-5 pr-24">{{review.review}}</div>
                </div>
            {% endfor %}
        </div>
        {% else %}
        <div class="mt-5">No reviews yet</div>
        {% endif %}
    </div>

{% endblock content %}

templates/rooms/room_photos.html
{% extends 'base.html' %}

{% block page_title %}{{room.name}} Photos{% endblock page_title %}

{% block search_bar %}{% endblock search_bar %}

{% block content %}
    <div class="container mx-auto mt-40 mb-24 flex flex-col">

        <div class="my-10 w-full flex justify-center items-center">
        <a href="{% url 'rooms:add-photo' room.pk %}" class="w-2/12 block border py-3 rounded-lg font-light text-white bg-blue-400 text-center">Upload</a>
        </div>
        
        {% for photo in room.photos.all %}
            <div class="mb-5 flex justify-between items-center border p-6 border-gray-300">
                <div class="flex items-center">
                    <img src="{{photo.file.url}}" alt="{{photo.caption}}" class="w-32 h-32">
                    <div class="text-xl ml-10">{{photo.caption}}</div>
                </div>
                <div class="flex flex-col w-1/6">
                    <a class="py-3 rounded-lg font-light text-white mb-5 text-center bg-green-500" href="{% url 'rooms:edit-photo' room.pk photo.pk %}">Edit</a>
                    <a class="py-3 rounded-lg font-light text-white  text-center bg-red-600" href="{% url 'rooms:delete-photo' room.pk photo.pk %}">Delete</a>
                </div>
            </div>
        {% endfor %}
        
        <div class="flex justify-center mt-5">
            <a href="{% url 'rooms:edit' room.pk %}" class="text-green-500 font-medium text-2xl">Back edit to room</a>
        </div>
    </div>
{% endblock content %}

templates/rooms/search.html
{% extends 'base.html' %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}

{% block content %}

    <div class="container mx-auto flex mt-40 mb-24 ">
        <div class="border p-6 border-gray-300 mr-20 w-3/12">
            <form method="GET" action="{% url 'rooms:search' %}" >
                <div class="flex items-center justify-center col-span-2">
                    <button class="mt-5 border py-3 rounded-lg font-light transition-all text-white bg-red-400 w-6/12 h-12 mb-10">Search</button>    
                </div>
                <div class="w-full">
                    {% for field in form %}
                        {% include 'mixins/search_form_input.html'  with field=field %}
                    {% endfor %}
                </div>
            </form>
        </div>
        {% if rooms.paginator.count >= 1 %}
        <div class="">
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 gap-5">
                {% for room in rooms %}
                    {% include 'mixins/room_card.html' with room=room %}
                {% endfor %}
            </div>

            <h5>
                {% if rooms.has_previous %}
                    <a href="{{ request.get_full_path }}&page={{rooms.previous_page_number}}">Previous</a>
                {% endif %}

                {% for page in rooms.paginator.page_range %}
                    <a 
                    href="{{ request.get_full_path }}&page={{page}}" 
                    class="{% if page == rooms.number %}text-red-500{% endif %}">
                        {{page}}
                    </a>
                {% endfor %}

                {% if rooms.has_next %}
                    <a href="{{ request.get_full_path }}&page={{rooms.next_page_number}}">Next</a>
                {% endif %}
            </h5>
        </div>
        {% else %}
            <div>No results</div>
        {% endif %}
    </div>

{% endblock content %}