config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(os.environ.get("DJANGO_ADMIN", "admin/"), admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("go/<int:host_pk>/<int:guest_pk>", views.go_conversation, name="go"),
    path("<int:pk>", views.ConversationDetailView.as_view(), name="detail"),
]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("add/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFabsView.as_view(), name="see-favs"),
]

reservations/urls.py
from django.urls import path
from . import views


app_name = "Reervations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>",
        views.create,
        name="create",
    ),
    path("<int:pk>", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:user>/list/", views.ReservationListView.as_view(), name="list"),
    path("<int:pk>/<str:verb>/", views.edit_reservation, name="edit"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.DeleteRoomView.as_view(), name="delete"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoview.as_view(),
        name="edit-photo",
    ),
]

lists/models.py
from django.db import models
from core import models as core_models


class List(core_models.TimeStampedModel):

    """List Model Definition"""

    name = models.CharField(max_length=80)
    user = models.OneToOneField(
        "users.User", related_name="list", on_delete=models.CASCADE
    )
    rooms = models.ManyToManyField("rooms.Room", related_name="lists", blank=True)

    def __str__(self):
        return self.name

    def count_rooms(self):
        return self.rooms.count()

    count_rooms.short_description = "# Rooms"

reservations/models.py
import datetime
from django.db import models
from django.utils import timezone
from core import models as core_models


class BookedDay(core_models.TimeStampedModel):
    day = models.DateField()
    reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Booked Day"
        verbose_name_plural = "Booked Days"

    def __str__(self):
        return str(self.day)


class Reservation(core_models.TimeStampedModel):

    """Reservation Model Definition"""

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_CONFIRMED, "Confirmed"),
        (STATUS_CANCELED, "Canceled"),
    )

    status = models.CharField(
        choices=STATUS_CHOICES, max_length=12, default=STATUS_PENDING
    )
    check_in = models.DateField()
    check_out = models.DateField()
    guest = models.ForeignKey("users.User", on_delete=models.CASCADE)
    room = models.ForeignKey("rooms.Room", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.room} - {self.check_in}"

    def in_progress(self):
        now = timezone.now().date()
        return now >= self.check_in and now <= self.check_out

    in_progress.boolean = True

    def is_finished(self):
        now = timezone.now().date()
        is_finished = now >= self.check_out
        if is_finished:
            BookedDay.objects.filter(reservation=self).delete()
        return is_finished

    is_finished.boolean = True

    def save(self, *args, **kwargs):
        if self.pk is None:
            start = self.check_in
            end = self.check_out
            difference = end - start
            existing_booked_day = BookedDay.objects.filter(
                reservation__room=self.room, day__range=(start, end)
            ).exists()
            if not existing_booked_day:
                super().save(*args, **kwargs)
                for i in range(difference.days + 1):
                    day = start + datetime.timedelta(days=i)
                    BookedDay.objects.create(day=day, reservation=self)
        else:
            return super().save(*args, **kwargs)

lists/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.urls import reverse
from rooms import models as room_models
from . import models


def toggle_room(request, room_pk):
    action = request.GET.get("action", None)
    room = room_models.Room.objects.get_or_none(pk=room_pk)
    if room is not None and action is not None:
        the_list, _ = models.List.objects.get_or_create(
            user=request.user, name="My Favourites Houses"
        )
        if action == "add":
            the_list.rooms.add(room)
        elif action == "remove":
            the_list.rooms.remove(room)
    return redirect(reverse("rooms:detail", kwargs={"pk": room_pk}))


class SeeFabsView(TemplateView):

    template_name = "lists/list_detail.html"

reservations/views.py
import datetime
from django.utils.translation import gettext_lazy as _
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import View, ListView
from django.shortcuts import redirect
from django.contrib import messages
from rooms import models as room_models
from reviews import forms as review_forms
from . import models


class CreateError(Exception):
    pass


def create(request, room, year, month, day):
    try:
        date_obj = datetime.datetime(year, month, day)
        room = room_models.Room.objects.get(pk=room)
        models.BookedDay.objects.get(day=date_obj, reservation__room=room)
        raise CreateError
    except (room_models.Room.DoesNotExist, CreateError):
        messages.error(request, "Can't resere that room")
        return redirect(reverse("core:home"))
    except models.BookedDay.DoesNotExist:
        if request.user.is_anonymous:
            messages.info(request, _("Login required"))
            return redirect(reverse("users:login"))
        else:
            reservation = models.Reservation.objects.create(
                check_in=date_obj,
                check_out=date_obj + datetime.timedelta(days=1),
                guest=request.user,
                room=room,
            )
            return redirect(
                reverse("reservations:detail", kwargs={"pk": reservation.pk})
            )


class ReservationDetailView(View):
    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        reservation = models.Reservation.objects.get_or_none(pk=pk)
        if not reservation or (
            reservation.guest != self.request.user
            and reservation.room.host != self.request.user
        ):
            raise Http404()
        form = review_forms.CreateReviewForm()
        return render(
            self.request,
            "reservations/detail.html",
            {"reservation": reservation, "form": form},
        )


def edit_reservation(request, pk, verb):
    reservation = models.Reservation.objects.get_or_none(pk=pk)
    if not reservation or (
        reservation.guest != request.user and reservation.room.host != request.user
    ):
        raise Http404()
    if verb == "confirm":
        reservation.status = models.Reservation.STATUS_CONFIRMED
    elif verb == "cancel":
        reservation.status = models.Reservation.STATUS_CANCELED
        models.BookedDay.objects.filter(reservation=reservation).delete()
    reservation.save()
    messages.success(request, "Reservation Updated")
    return redirect(reverse("reservations:detail", kwargs={"pk": pk}))


class ReservationListView(ListView):

    """Reservation List View Definition"""

    def get(self, request, user):
        reservations = models.Reservation.objects.filter(guest=user)
        return render(request, "reservations/list.html", {"reservations": reservations})

templates/reservations/detail.html
{% extends "base.html" %}
{% load review_check %}

{% block page_title %}
    Reservation {{reservation.check_in}}
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container  max-w-6xl h-full mx-auto mb-20 mt-28 flex flex-col">
        <div class="border-t border-l border-r bg-cover bg-center h-56 rounded-t-lg" style="background-image: url({{reservation.room.first_photo}});"></div>
        <div class="flex flex-col items-start border-l border-r border-t border-b">
            <div class="font-medium border-b py-8 px-5 w-full">
                {{reservation.check_in}} - {{reservation.check_out}}
                <span class="ml-3 {% if reservation.status == 'pending' %} text-yellow-500 {% elif reservation.status == 'canceled' %} text-red-500 {% else %} text-green-600 {% endif %}">
                    {{reservation.get_status_display}}
                </span>
            </div>
    
            <span class="text-2xl border-b p-5 mt-2 w-full">
                {{reservation.room.name}}
            </span>
    
            <div class="flex p-5 border-b w-full">
                <div class="flex flex-col items-center">
                    {% if reservation.room.host == user %}
                    {% include "mixins/user_avatar.html" with user=reservation.guest amount=12 %}
                    <span class="mt-2 text-gray-500">{{reservation.guest.first_name}}</span>
                    {% else %}
                    {% include "mixins/user_avatar.html" with user=reservation.room.host amount=12 %}
                    <span class="mt-2 text-gray-500">{{reservation.room.host.first_name}}</span>
                    {% endif %}
                </div>
                <div class="ml-5 flex flex-col justify-center">
                    {% if reservation.room.host == user %}
                    <span class="font-medium mb-px">Contact your Guest</span>
                    {% else %}
                    <span class="font-medium mb-px">Contact your Host</span>
                    {% endif %}
                    <a href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk %}" class="w-full py-2 rounded-lg font-light bg-blue-500 text-white flex items-center justify-center mt-2">
                        <div>Send a Message</div>
                    </a>
                    
                </div>
            </div>
            <div class="py-10 px-5 flex w-full">
            {% if reservation.status != 'canceled' %}
                {% if reservation.status == 'confirmed' and reservation.is_finished %}
                    {% review_check reservation as review %}
                    {% if review %}
                    <div class="">
                        <div class="flex items-center justify-between">
                            <div class="flex items-center">
                                <div class="mr-5">{% include 'mixins/user_avatar.html' with user=review.user amount=14 %}</div>
                                <div>
                                    <div class="font-medium">{{review.user.first_name}}</div>
                                    <div>{{review.created|date:"F Y"}}</div>
                                </div>
                            </div>
                            {% if review.user == user %}
                            <a href="{% url 'reviews:delete' reservation.room.pk review.pk %}" class="text-gray-400 hover:text-gray-700">
                                <i class="far fa-trash-alt"></i>
                            </a>
                            {% endif %}
                        </div>
                        <div class="mt-5 pr-24">{{review.review}}</div>
                    </div>

                    {% else %}
                    <div class="">
                        <div class="font-medium text-lg text-center w-full mb-5">Write your Review</div>
                        <form action="{% url 'reviews:create' reservation.room.pk %}" method="POST" class="w-1/2 mx-auto">
                            {% csrf_token %}
                            {{form}}
                            <button class="w-full py-3 rounded-lg font-light bg-green-600 mt-10 text-white">Submit Review</button>
                        </form>
                    </div>
                    {% endif %}
                {% else %}
                    {% if reservation.status == 'pending' %}
                        <div class="mr-5">
                            <a href="{% url 'reservations:edit' reservation.pk "cancel" %}" class="w-full py-3 rounded-lg font-light bg-red-500 block text-white px-3">Cancel Reservation</a>
                        </div>
                        {% if reservation.room.host == user %}
                            <div>
                                <a href="{% url 'reservations:edit' reservation.pk "confirm" %}" class="w-full py-3 rounded-lg font-light bg-green-600 text-white block px-3">Confirm Reservation</a>
                            </div>
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/reservations/list.html
{% extends 'base.html' %} 
{% load i18n %}
{% load static %}

{% block page_title %}
    Reservation List 
{% endblock page_title %} 

{% block content %} 


<div class="container mx-auto">

    
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5 mt-28">
        {% for reservation in reservations %}
            <div class="mb-10 px-2">
                <a href="{% url 'reservations:detail' reservation.pk%}">
                    <div class="h-96 md:h-80 lg:h-60 xl:h-60 bg-cover bg-center rounded-2xl" style="background-image: url('{{reservation.room.first_photo}}')"></div>
                    <div class="flex justify-between mt-3 mb-2">
                        <div class="flex w-10/12">
                            {% if reservation.room.host.superhost %}
                                <div class="uppercase font-medium text-xs px-2 py-0.5 border border-gray-700 rounded mr-2">superhost</div>
                            {% endif %}
                            <div class="text-sm text-gray-600 truncate">{{reservation.room.city}}, {{reservation.room.country.name}}</div>

                        </div>
                        <div class="text-sm flex items-center justify-center">
                        <i class="fas fa-star text-red-500 text-xs mr-1"></i> {{reservation.room.total_rating}}
                        </div>
                    </div>
                    <div class="text-black truncate">{{reservation.room.name}}</div>
                </a>
            </div>
        {% endfor %} 
    </div>
    
    
</div>
{% endblock content %}