config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(os.environ.get("DJANGO_ADMIN", "admin/"), admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("login/naver/", views.naver_login, name="naver-login"),
    path("login/naver/callback/", views.naver_callback, name="naver-callback"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>/", views.complate_verification, name="verify"),
    path("logout/", views.log_out, name="logout"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]

users/forms.py
from django import forms
from django.contrib.auth import password_validation
from . import models


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "E-mail"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Incorrect Password"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User Not Found"))


class SignUpForm(forms.Form):

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "First Name"})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Last Name"})
    )
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "E-mail"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"}),
        label="Confirm Password",
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError("E-mail already exists")
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError("Password does not match")
        else:
            return password

    def _post_clean(self):
        super()._post_clean()
        password = self.cleaned_data.get("password")
        if password:
            try:
                password_validation.validate_password(password)
            except forms.ValidationError as error:
                self.add_error("password", error)

    def save(self, *args, **kwargs):
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user = models.User.objects.create_user(email, email, password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = (
            "email",
            "first_name",
            "last_name",
            "gender",
            "bio",
            "avatar",
            "birthdate",
            "language",
            "currency",
        )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            user = models.User.objects.get(email=email)
            if user == self.instance:
                return email
            raise forms.ValidationError("E-mail already exists")
        except models.User.DoesNotExist:
            return email

users/views.py
import os
import uuid
import requests
from django.conf import settings
from django.http import HttpResponse
from django.contrib.auth.views import PasswordChangeView
from django.views.generic.edit import UpdateView
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.views.generic import FormView, DetailView
from django.core.files.base import ContentFile
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from . import forms, models, mixins


# class LoginView(View):
#     def get(self, request):
#         form = forms.LoginForm()
#         return render(request, "users/login.html", {"form": form})

#     def post(self, request):
#         form = forms.LoginForm(request.POST)
#         if form.is_valid():
#             email = form.cleaned_data.get("email")
#             password = form.cleaned_data.get("password")
#             user = authenticate(request, username=email, password=password)
#             if user is not None:
#                 login(request, user)
#                 return redirect(reverse("core:home"))
#         return render(request, "users/login.html", {"form": form})


class LoginView(mixins.LoggedOutOnlyView, SuccessMessageMixin, FormView):
    template_name = "users/login.html"
    form_class = forms.LoginForm
    success_message = "Welcome %(first_name)s"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data, first_name=self.request.user.first_name
        )

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            print(next_arg)
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    messages.info(request, f"See you later {request.user.first_name}")
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        user.verify_email()
        return super().form_valid(form)


def complate_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        messages.info(request, f"{request.user.email} is Verified!")
    except models.User.DoesNotExist:
        messages.warning(request, f"Sorry {request.user.first_name} Something is Wrong")
        pass
    return redirect(reverse("core:home"))


def github_login(request):
    base_url = "https://github.com/login/oauth/authorize?"
    client_id = os.environ.get("GH_ID")
    if bool(os.environ.get("DEBUG")):
        redirect_uri = "http://127.0.0.1:8000/users/login/github/callback"
    else:
        redirect_uri = "http://airbnb-challenge.eba-3m7n3idm.ap-northeast-2.elasticbeanstalk.com/users/login/github/callback"
    return redirect(
        f"{base_url}client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user&allow_signup=true"
    )


class GithubException(Exception):
    pass


def github_callback(request):
    try:
        base_url = "https://github.com/login/oauth/access_token?"
        code = request.GET.get("code", None)
        client_id = os.environ.get("GH_ID")
        client_secret = os.environ.get("GH_SECRET")
        if code is not None:
            token_request = requests.post(
                f"{base_url}client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            token_json = token_request.json()
            error = token_json.get("error", None)
            if error is not None:
                raise GithubException("Can't get access token")
            access_token = token_json.get("access_token")
            profile_request = requests.get(
                "https://api.github.com/user",
                headers={
                    "Authorization": f"token {access_token}",
                    "Accept": "application/json",
                },
            )
            profile_json = profile_request.json()
            username = profile_json.get("login", None)
            if username is not None:
                name = profile_json.get("name")
                email = profile_json.get("email")
                bio = profile_json.get("bio")
                try:
                    user = models.User.objects.get(email=email)
                    if user.login_method != models.User.LOGIN_GITHUB:
                        raise GithubException(f"Please log in with {user.login_method}")
                except models.User.DoesNotExist:
                    user = models.User.objects.create(
                        email=email,
                        first_name=name,
                        username=email,
                        bio=bio,
                        login_method=models.User.LOGIN_GITHUB,
                        email_verified=True,
                    )
                    user.set_unusable_password()
                    user.save()
                    avatar_url = profile_json.get("avatar_url", None)
                    if avatar_url is not None:
                        photo_request = requests.get(avatar_url)
                        user.avatar.save(
                            f"{name}-avatar.jpg", ContentFile(photo_request.content)
                        )
                messages.success(request, f"Welcome Back {user.first_name}")
                login(request, user)
                return redirect(reverse("core:home"))
            else:
                raise GithubException("Can't get your profile")
        else:
            raise GithubException("Can't get your code")
    except GithubException as error:
        messages.error(request, error)
        return redirect(reverse("users:login"))


def kakao_login(request):
    base_url = "https://kauth.kakao.com/oauth/authorize?"
    client_id = os.environ.get("KAKAO_ID")
    if bool(os.environ.get("DEBUG")):
        redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
    else:
        redirect_uri = "http://airbnb-challenge.eba-3m7n3idm.ap-northeast-2.elasticbeanstalk.com/users/login/kakao/callback"
    return redirect(
        f"{base_url}client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        base_url = "https://kauth.kakao.com/oauth/token?"
        code = request.GET.get("code", None)
        client_id = os.environ.get("KAKAO_ID")
        if bool(os.environ.get("DEBUG")):
            redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
        else:
            redirect_uri = "http://airbnb-challenge.eba-3m7n3idm.ap-northeast-2.elasticbeanstalk.com/users/login/kakao/callback"
        if code is not None:
            token_request = requests.post(
                f"{base_url}grant_type=authorization_code&client_id={client_id}&code={code}&redirect_uri={redirect_uri}"
            )
            token_json = token_request.json()
            error = token_json.get("error")
            if error is not None:
                raise KakaoException("Can't get access token")

            access_token = token_json.get("access_token")
            profile_request = requests.get(
                "https://kapi.kakao.com/v2/user/me",
                headers={"Authorization": f"Bearer {access_token}"},
            )
            profile_json = profile_request.json()
            email = profile_json.get("kakao_account").get("email", None)
            if email is None:
                raise KakaoException("Please agree with giving your email to us")
            profile = profile_json.get("kakao_account").get("profile", None)
            if profile is None:
                raise KakaoException("Kakao profile does not exist")
            else:
                nickname = profile.get("nickname")
                profile_image = profile.get("profile_image_url")
                try:
                    user = models.User.objects.get(email=email)
                    if user.login_method != models.User.LOGIN_KAKAO:
                        raise KakaoException(f"Please log in with {user.login_method}")
                except models.User.DoesNotExist:
                    user = models.User.objects.create(
                        email=email,
                        username=email,
                        first_name=nickname,
                        login_method=models.User.LOGIN_KAKAO,
                        email_verified=True,
                    )
                    user.set_unusable_password()
                    user.save()
                    if profile_image is not None:
                        photo_request = requests.get(profile_image)
                        user.avatar.save(
                            f"{nickname}-avatar.jpg", ContentFile(photo_request.content)
                        )
                messages.success(request, f"Welcome Back {user.first_name}")
                login(request, user)
                return redirect(reverse("core:home"))

templates/users/change-password.html
{% extends 'base.html' %}

{% block page_title %}Update Profile{% endblock page_title %}

{% block search_bar %}{% endblock search_bar %}

{% block content %}
    <div class="container md:w-6/12 lg:w-5/12 xl:w-1/4 mx-auto mt-40 mb-24 flex flex-col items-center border p-6 border-gray-300">
        {% include 'mixins/auth/auth_form.html' with form=form cta="Update Password" %}
        
    </div>
{% endblock content %}

templates/users/login.html
{% extends 'base.html' %}

{% block page_title %}Login{% endblock page_title %}

{% block search_bar %}{% endblock search_bar %}

{% block content %}
    <div class="container md:w-6/12 lg:w-5/12 xl:w-1/4 mx-auto mt-40 mb-24 flex flex-col items-center border p-6 border-gray-300">
        {% include 'partials/social_login.html' %}

        {% include 'mixins/auth/auth_form.html' with form=form cta="Log in" %}

        <div class="mt-5 flex">
            <div class="mr-3">Don't Have an account?</div>
            <a href="{% url 'users:signup' %}" class="text-red-500 font-medium">Sign up</a>
        </div>
    </div>
{% endblock content %}

templates/users/signup.html
{% extends 'base.html' %}

{% block page_title %}Sign Up{% endblock page_title %}

{% block search_bar %}{% endblock search_bar %}

{% block content %}
    <div class="container md:w-6/12 lg:w-5/12 xl:w-1/4 mx-auto mt-40 mb-24 flex flex-col items-center border p-6 border-gray-300">
        {% include 'partials/social_login.html' %}

        {% include 'mixins/auth/auth_form.html' with form=form cta="Sign Up" %}

        <div class="mt-5 flex">
            <div class="mr-3">Already have an account?</div>
            <a href="{% url 'users:login' %}" class="text-red-500 font-medium">Log in</a>
        </div>
    </div>
{% endblock content %}

templates/users/update-password.html
{% extends 'base.html' %}

{% block page_title %}Update Password{% endblock page_title %}

{% block search_bar %}{% endblock search_bar %}

{% block content %}
    <div class="container md:w-6/12 lg:w-5/12 xl:w-1/4 mx-auto mt-40 mb-24 flex flex-col items-center border p-6 border-gray-300">
        {% include 'mixins/auth/auth_form.html' with form=form cta="Update Password" %}
        
    </div>
{% endblock content %}

templates/users/update-profile.html
{% extends 'base.html' %}

{% block page_title %}Update Profile{% endblock page_title %}

{% block search_bar %}{% endblock search_bar %}

{% block content %}
    <div class="container md:w-6/12 lg:w-5/12 xl:w-1/4 mx-auto mt-40 mb-24 flex flex-col items-center border p-6 border-gray-300">
        {% include 'mixins/edit/edit_form.html' with form=form cta="Update Profile" %}
        {% if object.login_method == "email" %}
            <div class="mt-5 flex">
                <a href="{% url 'users:password' %}" class="text-green-500 font-medium">Change Password</a>
            </div>
        {% endif %}
        
    </div>
{% endblock content %}

templates/users/user_detail.html
{% extends 'base.html' %}

{% block page_title %}
    {{user_obj.first_name}}'s Profile
{% endblock page_title %}

{% block content %}
    <div class="h-full">
        <div class="container md:w-6/12 lg:w-5/12 xl:w-1/4 mx-auto mt-40 mb-24 flex flex-col items-center border p-6 border-gray-300">
            {% include 'mixins/user_avatar.html' with user=user_obj amount=20 %}
            {% if user_obj.superhost %}
                    <div class="border border-gray-00 p-1 rounded uppercase text-xs mt-3">superhost</div>
            {% endif %}
            <div class="text-3xl mt-5 flex items-center justify-center">
                <div>{{user_obj.first_name}}</div>
            </div>
            <div class="mt-5 text-lg text-center">{{user_obj.bio}}</div>
            
            {% if user == user_obj %}
                <a class="btn-link text-center mt-5" href="{% url 'users:update' %}">Edit Profile</a>
            {% endif %}
        </div>

        {% if user_obj.rooms.count > 0 %}
            <div class="container mx-auto flex flex-col items-center">
                <h3 class="text-2xl">{{user_obj.first_name}}'s Rooms</h3>
                <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5 mt-20">
                {% for room in user_obj.rooms.all %}
                    {% include 'mixins/room_card.html' with room=room %}
                {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>

{% endblock content %}